In [45]:
from sklearn.preprocessing import StandardScaler
import pandas as pd
df = pd.read_csv('C:/Users/Yerassyl/Desktop/data mining/shanghai_ranking_2024.csv')
numeric_df = df.select_dtypes(include=['float64', 'int64'])
scaler = StandardScaler()
df_standardized = pd.DataFrame(scaler.fit_transform(numeric_df), columns=numeric_df.columns)
print(df_standardized.head())

print(df.head())
categorical_columns = df.select_dtypes(include=['object']).columns
print(categorical_columns)
df_encoded = pd.get_dummies(df, columns=categorical_columns, drop_first=True)
print(df_encoded.head())

print(df.columns)
print(df.head())
bins = [0, 50, 100, 150, 200, 300]
labels = ['0-50', '51-100', '101-150', '151-200', '201+']
df['Award'] = pd.cut(df['Award'], bins=bins, labels=labels, right=True)
print(df.head())

     Alumni     Award      Hici       N&S       PUB       PCP
0  9.456229  8.150362  8.156736  8.411022  4.744016  7.508463
1  4.039394  7.364312  5.698721  6.896707  2.777304  4.541217
2  6.673541  6.901416  4.063090  5.664562  1.753737  6.132843
3  7.297417  7.600127  3.140192  4.629937  2.345944  4.654904
4  6.019955  6.351181  3.304669  4.912107  1.607513  4.075097
  Rank                              University_Name National/Regional Rank  \
0    1                           Harvard University                      1
1    2                          Stanford University                      2
2    3  Massachusetts Institute of Technology (MIT)                      3
3    4                      University of Cambridge                      1
4    5           University of California, Berkeley                      4

   Alumni  Award   Hici    N&S    PUB   PCP
0   100.0   97.1  100.0  100.0  100.0  85.7
1    45.3   88.1   73.1   83.9   73.1  59.6
2    71.9   82.8   55.2   70.8   59.1  73.6
3    78.2   90.8   45.1   59.8   67.2  60.6
4    65.3   76.5   46.9   62.8   57.1  55.5
Index(['Rank', 'University_Name', 'National/Regional Rank'], dtype='object')
   Alumni  Award   Hici    N&S    PUB   PCP  Rank_10  Rank_100  Rank_101-150  \
0   100.0   97.1  100.0  100.0  100.0  85.7    False     False         False
1    45.3   88.1   73.1   83.9   73.1  59.6    False     False         False
2    71.9   82.8   55.2   70.8   59.1  73.6    False     False         False
3    78.2   90.8   45.1   59.8   67.2  60.6    False     False         False
4    65.3   76.5   46.9   62.8   57.1  55.5    False     False         False

   Rank_11  ...  National/Regional Rank_8  National/Regional Rank_8-10  \
0    False  ...                     False                        False
1    False  ...                     False                        False
2    False  ...                     False                        False
3    False  ...                     False                        False
4    False  ...                     False                        False

   National/Regional Rank_8-11  National/Regional Rank_9  \
0                        False                     False
1                        False                     False
2                        False                     False
3                        False                     False
4                        False                     False

   National/Regional Rank_9-10  National/Regional Rank_9-11  \
0                        False                        False
1                        False                        False
2                        False                        False
3                        False                        False
4                        False                        False

   National/Regional Rank_9-12  National/Regional Rank_9-15  \
0                        False                        False
1                        False                        False
2                        False                        False
3                        False                        False
4                        False                        False

   National/Regional Rank_92-114  National/Regional Rank_99-114
0                          False                          False
1                          False                          False
2                          False                          False
3                          False                          False
4                          False                          False

[5 rows x 1220 columns]
Index(['Rank', 'University_Name', 'National/Regional Rank', 'Alumni', 'Award',
       'Hici', 'N&S', 'PUB', 'PCP'],
      dtype='object')
  Rank                              University_Name National/Regional Rank  \
0    1                           Harvard University                      1
1    2                          Stanford University                      2
2    3  Massachusetts Institute of Technology (MIT)                      3
3    4                      University of Cambridge                      1
4    5           University of California, Berkeley                      4

   Alumni  Award   Hici    N&S    PUB   PCP
0   100.0   97.1  100.0  100.0  100.0  85.7
1    45.3   88.1   73.1   83.9   73.1  59.6
2    71.9   82.8   55.2   70.8   59.1  73.6
3    78.2   90.8   45.1   59.8   67.2  60.6
4    65.3   76.5   46.9   62.8   57.1  55.5
  Rank                              University_Name National/Regional Rank  \
0    1                           Harvard University                      1
1    2                          Stanford University                      2
2    3  Massachusetts Institute of Technology (MIT)                      3
3    4                      University of Cambridge                      1
4    5           University of California, Berkeley                      4

   Alumni   Award   Hici    N&S    PUB   PCP
0   100.0  51-100  100.0  100.0  100.0  85.7
1    45.3  51-100   73.1   83.9   73.1  59.6
2    71.9  51-100   55.2   70.8   59.1  73.6
3    78.2  51-100   45.1   59.8   67.2  60.6
4    65.3  51-100   46.9   62.8   57.1  55.5